### ISSUE TITLE
error_log vfsStream

### ISSUE THREAD

**Issue by gimler** [mikey179/vfsStream#152]
Can't redirect the error_log to vfsStream.

```
<?php

require_once __DIR__ . "/vendor/autoload.php";

use org\bovigo\vfs\vfsStream;

$vfsRoot = vfsStream::setup('error');
$logFile = vfsStream::newFile('error.log');
$vfsRoot->addChild($logFile);

ini_set('error_log', vfsStream::url('error/error.log'));

error_log(ini_get('error_log'));

var_dump($logFile->getContent());
```

**Comment by mikey179** [comment]
I think there's nothing that can be done about this in vfsStream. In the case depicted above the call leads to https://github.com/php/php-src/blob/c6982995504b6e21e8a5ade29cfb16a55196dc43/main/main.c#L646  which will simply fall back to standard error_log target if it can't open the configured path. And it can't open the configured path because it doesn't use any of the stream wrapper stuff. Most likely because it can't rely on it at this place.

Interestingly, `error_log('foo', 3, vfsStream::url('error/error.log'));` works because in this case it uses the internal stream wrapper: https://github.com/php/php-src/blob/6035ebd4a6c2c81eaf7b2ac71f6e23cb04e2c000/ext/standard/basic_functions.c#L4760

**Comment by mikey179** [comment]
Added this to the list of [known issues](https://github.com/mikey179/vfsStream/wiki/Known-Issues) under issues that can't be fixed within vfsStream.
