### ISSUE TITLE
File rights are ignored with unlink

### ISSUE THREAD

**Issue by lovenunu** [mikey179/vfsStream#158]
Hello,
I found that even if a file is not writable, `unlink` will return true and the file will be removed from directory with no error.

Example:
```php
<?php
$root = \org\bovigo\vfs\vfsStream::setup();
$file = new \org\bovigo\vfs\vfsStreamFile('foo', 0);
$root->addChild($file);

// This should output: bool(false)
// Acutal result: bool(true)
var_dump(unlink($file->url()));
```

I'm doing a pull request to fix this problem :)

**Comment by lovenunu** [comment]
My bad, I didn't know it was expected to work this way.

**Comment by mikey179** [comment]
Yes, that's how Linux works. See https://speakerdeck.com/mikey179/testing-filesystem-related-code-with-vfsstream-june-30-2016-phpugmrn?slide=22 for a test you can perform on your system to see for yourself. In short: whether you can delete a file/directory doesn't depend on the rights you have for the file/directory you want to delete, but on the rights of the directory you want to delete in. The reason is that the deletion changes the directory where it is in, and not the file/directory that is about to be deleted.

But I appreciate your effort of providing a PR together with the bug report. :)
