### ISSUE TITLE
Testing paths starting with __DIR__

### ISSUE THREAD

**Issue by ddlzz** [mikey179/vfsStream#163]
Hi there. In some project I have code like this:

```
$fileName = __DIR__ . '/file.txt';
file_put_contents($fileName, 'test contents');
// ...
if (file_exists($fileName) {
unlink($fileName);
}
```

It is just an example, in real code I used __DIR__ in bootstrap.php to preserve correct path relations in the whole project. Is there a way to mock a file with path, that is equal to __DIR__ ?

**Comment by ddlzz** [comment]
I tried this
`
        $root = vfsStream::setup('var');
        $root->setParentPath('test');
        $correctCookie = vfsStream::newFile('test.txt')
            ->withContent('test content')
            ->at($root);
        var_dump(file_get_contents($correctCookie->url()));
`

but with the line 
        `
$root->setParentPath('test');
`
it all stops working.

**Comment by mikey179** [comment]
Well, `setParentPath()` is not to be called by an external user, as the doc comment says `@internal`. ;-) Not sure why you want to call it in your example?

Regarding the `__DIR__` issue, vfsStream mock pathes always have to start with `vfs://` as otherwise PHP doesn't know it has to call into vfsStream instead of the real file system. Your example with vfsStream would probably look something like this:

```php
$root = vfsStream::setup();
$fileName = $root->url() . '/file.txt';
file_put_contents($fileName, 'test contents');
// ...
if (file_exists($fileName) {
    unlink($fileName);
}
```

**Comment by ddlzz** [comment]
Thanks! I realized that the usage of `__DIR__` as a constant was a flaw in architecture of my project and I solved this by passing `Filesystem` class to my settings
