### ISSUE TITLE
Unlinking file on VFS directory without write permissions returns false but no warning

### ISSUE THREAD

**Issue by btruhand** [mikey179/vfsStream#164]
I'm testing out unlinking file on directory without write permissions using https://secure.php.net/manual/en/function.unlink.php

Reading the comments people say that unlinking a file that is under a non-writable directory for the user will return false and cause a warning. I tested it in Mac and that's true

Here's the test code:
```php
<?php

$testDir = $_SERVER['HOME'] . '/test';
var_dump(unlink($testDir . '/t'));
```

And here's the directory state
```
$ > ls -al
total 0
-rw-r--r--   1 btara.truhandarien     0B Nov 22 14:44 t
drwxr-xr-x+ 63 btara.truhandarien   2.1K Nov 22 14:43 ../
dr-xr-xr-x   3 btara.truhandarien   102B Nov 22 14:44 ./
```

Running the above PHP code I get
```
$ > php test.php

Warning: unlink(/Users/btara.truhandarien/test/t): Permission denied in /Users/btara.truhandarien/vagrant-entf/apps/entfbatch-wrap/entfbatch/src/tests/test.php on line 4

Call Stack:
    0.0003     228432   1. {main}() /Users/btara.truhandarien/vagrant-entf/apps/entfbatch-wrap/entfbatch/src/tests/test.php:0
    0.0003     228768   2. unlink() /Users/btara.truhandarien/vagrant-entf/apps/entfbatch-wrap/entfbatch/src/tests/test.php:4

/Users/btara.truhandarien/vagrant-entf/apps/entfbatch-wrap/entfbatch/src/tests/test.php:4:
bool(false)
```

However when testing it out with vfsStream I realized I get no warnings. Here is the test code with vfsStream:
```php
    public function testUnlinkingFileInVfsDirectoryNotPermittedToWriteTo()
    {
        $file = $this->makeBasicTestFile();
        chmod($this->vfs->url(), 0555);
        $this->assertFalse(FileUtilities::unlinkFile($file->url()));
    }
```

I know I don't get a warning because inside ```unlinkFile``` I have a set an error handler and it will throw if I were to use a real directory

Is it possible to trigger a warning for this, same like real file system?

**Comment by robfrawley** [comment]
I have a similar situation using this library with my PHPUnit tests. Take the following short example:

**The root virtual FS is created in the `setUp()` method of my PHPUnit unit test class definition:**

```php
$root = vfsStream::setup('php-unit', 0777);
$root->chown(getmyuid());
$root->chgrp(getmygid());
```
**This specific virtual file is created in one of the unit tests methods for a specific test case:**
```php
$file = new vfsStreamFile('file.ext', 0004);
$file->chown(0);
$file->chgrp(0);
$file->content('foobar');
$file->at($root);
```
**And this is the code that is called, having been given the value of `$file->url()`:**
```php
if (false === @unlink($this->file))) {
    throw new FileOperationException(sprintf('Failed to remove file "%s": %s.', $this->file, Interpreter::lastErrorMessage()));
}
```

__The exception is never thrown__, because for some reason *it allows the file to be deleted, despite only having read permission on it.* The passed permission of `0004` should only allow reading.

I checked the output of `is_readable()` and `is_writable()` and they both output the expected boolean results, `true` and `false`, respectively. For whatever reason, though, looking at the return of `unlink()` on the same file shows that `true` is returned.

What's going on? Any ideas?

**Comment by mikey179** [comment]
See issue #68: there is no way to implement this properly so that vfsStream knows when to issue a warning and when not.
