### ISSUE TITLE
Unlinking a file with only read permissions (0004) on VFS does not return false.

### ISSUE THREAD

**Issue by robfrawley** [mikey179/vfsStream#166]
I am trying to use this library to mock a bunch of FS-based tests currently handled without abstraction. I am having trouble getting the expected results when it comes to `unlink()`. Take the following setup.

**The root virtual FS is created in the `setUp()` method of my PHPUnit unit test class definition:**

```php
$root = vfsStream::setup('php-unit', 0777);
$root->chown(getmyuid());
$root->chgrp(getmygid());
```
**This specific virtual file is created in one of the unit tests methods for a specific test case:**
```php
$file = new vfsStreamFile('file.ext', 0004);
$file->chown(0);
$file->chgrp(0);
$file->content('foobar');
$file->at($root);
```
**And this is the code that is called, having been given the value of `$file->url()`:**
```php
if (false === @unlink($this->file))) {
    throw new FileOperationException(sprintf('Failed to remove file "%s": %s.', $this->file, Interpreter::lastErrorMessage()));
}
```

__The exception is never thrown__, because for some reason *it allows the file to be deleted, despite only having read permission on it.* The passed permission of `0004` should only allow reading.

I checked the output of `is_readable()` and `is_writable()` and they both output the expected boolean results, `true` and `false`, respectively. For whatever reason, though, looking at the return of `unlink()` on the same file shows that `true` is returned.

What's going on? Any ideas?

**Comment by robfrawley** [comment]
I should point out that changing the permissions to `0000`, which should provide no rights at all, still allows `unlink()` to complete and return `true`. This is using the `2.0.x-dev` branch on Packagist.

**Comment by robfrawley** [comment]
Also quite odd, the behavior seems to change significantly between `1.6.5` and `2.0.x-dev`. Given the same example as above, I recieve different results for `is_readable()`, `is_writeable()`, `file_exists()`, and `unlink()`.

```php
$root = vfsStream::setup('php-unit', 0777);
$root->chown(vfsStream::getCurrentUser());
$root->chgrp(vfsStream::getCurrentGroup());

$file = new vfsStreamFile('file.ext', 0400);
$file->chown(vfsStream::getCurrentUser() + 1);
$file->chgrp(vfsStream::getCurrentGroup() + 1);
$file->content('foobar');
$root->->addChild($file);

var_dump(is_readable($file->url()));
var_dump(is_writable($file->url()));
var_dump(file_exists($file->url()));
var_dump(unlink($file->url()));
```
Using version **`1.6.5`** I get the following:
```
false
false
true
true
```
Using version **`2.0.x-dev`** I get the following:
```
true
false
false
true
```
For both of these, I **should** get:
```
false
false
true
false
```

**Comment by mikey179** [comment]
Regarding unlinking a readonly file: that's exactly how Linux works. See https://speakerdeck.com/mikey179/testing-filesystem-related-code-with-vfsstream-june-30-2016-phpugmrn?slide=22 for a test you can perform on your system to see for yourself. In short: whether you can delete a file/directory doesn't depend on the rights you have for the file/directory you want to delete, but on the rights of the directory the file is in. The reason is that the deletion changes the directory where it is in, and not the file/directory that is about to be deleted.

Regarding differences between 1.6.5 and 2.0.0-dev: the change with `is_readable` is indeed odd. I'll open a separate bug for this. The result for `unlink()` is correct, see explanation above.
