### ISSUE TITLE
Symbolic Links

### ISSUE THREAD

**Issue by hborawski** [mikey179/vfsStream#89]
In a testing situation, I will need the php builtin `readlink` to resolve a symbolic link in the virtual filesystem.

I will gladly implement this, and would just like to know of any existing code towards this feature so that it may be utilized (I suspect code does exists because the `const` for `TYPE_LINK` exists in `vfsStreamContent` already).

**Comment by malc0mn** [comment]
Is this one ready for release? Anything that can be done to help?

**Comment by mikey179** [comment]
We started but never got around to finish it. As for now I think this feature is dead - mostly because it also requires changes in PHP and I don't see anyone going ahead to make those changes. Also, I believe the chance of those changes being merged into PHP are quite low, as to my knowledge they would only be beneficial for vfsStream and nothing else. But if you want to, you can take over the [RFC](https://wiki.php.net/rfc/linking_in_stream_wrappers), provide an implementation and see if it gets accepted.

**Comment by malc0mn** [comment]
Thanks for the status update. I must admit that I totally missed the part about the RFC, otherwise I wouldn't have even asked.
Quite bold to go there though as I do agree that linking in stream wrappers would only be useful for vfsStream :smile:

**Comment by mikey179** [comment]
Closing this for now.

**Comment by pascal-chenevas** [comment]
Hi!

I am in the same case as @hborawski. I have some tests scenarios that must involve symbolic links.
May I ask please, what is the state of this topic in the project? 
Did you solve this with any workaround?
Thank you in advance!
